In [3]:
import numpy as np


In [4]:
myList=[1,2,3,4]
myArr=np.array(myList)


In [5]:
type(myArr)

numpy.ndarray

## shape & reshape

In [6]:


myArr.shape

(4,)

In [7]:
l1=[1,2,3,4,5]
l2=[6,7,8,9,10]
l3=[0,2,4,6,8]
mulArr=np.array([l1,l2,l3])

In [8]:
mulArr.shape

(3, 5)

In [9]:
mulArr.reshape(5,3)

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10,  0,  2],
       [ 4,  6,  8]])

# Indexing


In [10]:
mulArr[:2,1:2]


array([[2],
       [7]])

In [13]:
mulArr[3:,0:]

array([], shape=(0, 5), dtype=int32)

In [14]:
mulArr[:,:]

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [ 0,  2,  4,  6,  8]])

In [15]:
mulArr[1:,:2]

array([[6, 7],
       [0, 2]])

# Arange Function
### Basically to generate the numbers in array between the given range

In [19]:
a1=np.arange(0,30,step=2)

In [20]:
a1

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28])

# copy function and broadcasting
## copy creates anither memory location to store the value.

In [21]:
a1[4:8]=100

In [22]:
a1

array([  0,   2,   4,   6, 100, 100, 100, 100,  16,  18,  20,  22,  24,
        26,  28])

In [23]:
a2=a1.copy()
a2[5:11]=300

In [24]:
a2

array([  0,   2,   4,   6, 100, 300, 300, 300, 300, 300, 300,  22,  24,
        26,  28])

In [25]:
a1

array([  0,   2,   4,   6, 100, 100, 100, 100,  16,  18,  20,  22,  24,
        26,  28])

# For EDA (arthematic operations)

In [31]:
print(a1)
print(a1+2)
print(a1*2)
print(a1//2)
print(a1%2)

[  0   2   4   6 100 100 100 100  16  18  20  22  24  26  28]
[  2   4   6   8 102 102 102 102  18  20  22  24  26  28  30]
[  0   4   8  12 200 200 200 200  32  36  40  44  48  52  56]
[ 0  1  2  3 50 50 50 50  8  9 10 11 12 13 14]
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]


In [40]:
print(a1)
print(a2)
newArr1=a1*a2
print(newArr1)
newArr1.shape

[  0   2   4   6 100 100 100 100  16  18  20  22  24  26  28]
[  0   2   4   6 100 300 300 300 300 300 300  22  24  26  28]
[    0     4    16    36 10000 30000 30000 30000  4800  5400  6000   484
   576   676   784]


(15,)

# For EDA (comparison)

In [33]:
a1<4

array([ True,  True, False, False, False, False, False, False, False,
       False, False, False, False, False, False])

In [35]:
#but we also want values which is less than 4 or any given number
a1[a1<4]

array([0, 2])

# np.ones

In [42]:
np.ones(4,dtype=int)

array([1, 1, 1, 1])

In [45]:
np.ones((2,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

# Random Distribution


In [46]:
np.random.rand(3,3)

array([[0.38972111, 0.73285026, 0.71087903],
       [0.0726997 , 0.28267711, 0.63211476],
       [0.57259708, 0.45580794, 0.90130127]])

In [49]:
arrx=np.random.randn(4,4)

In [50]:
arrx

array([[-2.94254493, -0.25163116,  0.08190038, -0.59323749],
       [-1.32622559, -0.34131422, -0.98164326, -1.28640765],
       [-1.02015644,  0.76012889,  0.75090094, -0.18872366],
       [-0.778829  , -0.15109812, -0.7493988 ,  0.02140007]])

In [54]:
np.random.randint(0,100,8).reshape(2,4)

array([[47, 60, 49, 73],
       [79, 51, 81, 59]])

In [57]:
np.random.random_sample((1,5))

array([[0.57114151, 0.18780241, 0.29673943, 0.08541797, 0.87691226]])